

export const WEBSITE_META = {
    TITLE_TEMPLATE: '%s | Just Diego',
    DEFAULT_TITLE: 'Just Diego - Business Solutions',
    KEYWORDS: [
        "diego rodriguez developer",
        "diego rodriguez portfolio",
        "diego rodriguez automation",
        "just diego solutions",
        "just diego automation",
        "devops consultant spain",
        "freelance developer europe",
        "web automation expert",
        "business process automation",
        "infrastructure automation",
        "backend development expert",
        "nodejs expert",
        "typescript developer",
        "linux server expert",
        "cloud automation",
        "digital transformation consulting",
        "ci/cd specialist",
        "software engineering",
        "infrastructure as code",
        "tech problem solver",
        "professional web development",
        "scalable systems consultant",
        "rapid deployment solutions",
        "custom business automation",
        "remote developer poland",
        "remote backend developer",
        "efficient web solutions",
        "web performance optimization",
        "system integration expert",
        "process optimization",
        "it consulting diego",
        "tech lead just diego",
        "automate your business just diego",
        "cloud vps automation spain",
        "migrate to cloud with just diego",
        "web backend optimization diego rodriguez",
        "fast project delivery web dev",
        "managed infrastructure just diego",
        "digital business growth spain",
        "justdiego.com reviews",
        "diego rodriguez client testimonials",
        "just diego coding portfolio",
        "case studies just diego",
        "trusted by businesses diego rodriguez",
        "top developer diego rodriguez",
        "business automation consultant",
        "reduce business costs automation",
        "devops automation expert",
        "workflow automation diego rodriguez",
        "automate repetitive tasks business",
        "manual process automation",
        "legacy systems automation",
        "business digital transformation expert",
        "integrate business software automation",
        "automate invoices and billing",
        "automate lead generation",
        "integrate crm automation",
        "optimize business workflow",
        "business process optimization expert",
        "business data synchronization",
        "automate daily business tasks",
        "cloud migration automation",
        "ci/cd pipeline automation consultant",
        "infrastructure as code business",
        "api integration for business",
        "automate reporting solutions",
        "reduce human error automation",
        "enterprise automation solutions",
        "cost reduction through automation",
        "process automation for smbs",
        "backoffice automation expert",
        "digital operations consultant",
        "automate sales funnel",
        "backend systems optimization",
        "process automation spain",
        "business solutions diego rodriguez",
        "business automation expert",
        "digital solutions provider",
        "web development spain",
        "software development europe",
        "cloud solutions spain",
        "it solutions provider",
        "business efficiency expert",
        "remote work solutions",
        "agile development spain",
        "justdiego business solutions",
        "justdiego",
        "just diego",
        "justdiego.com"
    ],
    AUTHOR: 'Diego Rodriguez',
    LANGUAGE: 'en-US',
} as const;