name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: ["dewstouh"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Component
        - New Page/Section
        - Performance Improvement
        - Developer Experience
        - Accessibility
        - SEO/Analytics
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: |
        As a [type of user], I want to [action] so that [benefit].
        
        Example scenario:
        1. User does X
        2. User expects Y
        3. Feature enables Z
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other sites/apps.
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, constraints, or requirements to consider?
      placeholder: |
        - Should work on mobile and desktop
        - Needs to be accessible
        - Should integrate with existing systems
        - Performance considerations

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - "Yes, I can implement this feature"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "Yes, I can help with design"
        - "No, but I'd like to see it implemented"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples about the feature request.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that might be similar
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true
