services:
  justdiego:
    build:
      context: ../../..
      dockerfile: docker/images/justdiego/Dockerfile
    container_name: justdiego-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=DATABASE_URL
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Database
  postgres:
    image: postgres:15-alpine
    container_name: justdiego-postgres
    environment:
      POSTGRES_DB: justdiego
      POSTGRES_USER: justdiego
      POSTGRES_PASSWORD: justdiego_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U justdiego"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: justdiego-network
